import { WeaponSlot } from "../../league-core/src/types/tdm"

const weaponNames = {
  "dagger": "Dagger",
  "bat": "Bat",
  "bottle": "Bottle",
  "crowbar": "Crowbar",
  "unarmed": "Unarmed",
  "flashlight": "Flashlight",
  "golfclub": "Golfclub",
  "hammer": "Hammer",
  "hatchet": "Hatcher",
  "knuckle": "Knuckle",
  "knife": "Knife",
  "machete": "Machete",
  "switchblade": "Switchblade",
  "nightstick": "Nightstick",
  "Pipe Wrench": "Pipe Wrench",
  "battleaxe": "Battleaxe",
  "poolcue": "Poolcue",
  "stone_hatchet": "Stone Hatchet",
  "pistol": "Pistol",
  "pistol-mk2": "Pistol MK2",
  "combatpistol": "Combat Pistol",
  "appistol": "AP Pistol",
  "stungun": "Shotgun",
  "pistol50": "Pistol .50",
  "snspistol": "SNS Pistol",
  "snspistol-mk2": "SNS Pistol MK2",
  "heavypistol": "Heavy Pistol",
  "vintagepistol": "Vintage Pistol",
  "flaregun": "Flaregun",
  "marksmanpistol": "Marksman Pistol",
  "revolver": "Revolver",
  "revolver_mk2": "Revolver MK2",
  "doubleaction": "Double Action",
  "up-n-atomizer": "Up-N-Atomizer",
  "microsmg": "Micro SMG",
  "smg": "SMG",
  "smg-mk2": "SMG MK2",
  "assaultsmg": "Assault SMG",
  "combatpdw": "Combat PDW",
  "machinepistol": "Machine Pistol",
  "minismg": "Mini SMG",
  "unholyhellbringer": "Unholy Hellbringer",
  "pumpshotgun": "Pump Shotgun",
  "pumpshotgun-mk2": "Pump Shotgun MK2",
  "sawnoffshotgun": "Sawed-off Shotgun",
  "Assault Shotgun": "Assault Shotgun",
  "bullpupshotgun": "Bullpup Shotgun",
  "musket": "Musket",
  "heavyshotgun": "Heavy Shotgun",
  "dbshotgun": "DB Shotgun",
  "sweepershotgun": "Sweeper Shotgun",
  "assaultrifle": "Assault Rifle",
  "assaultrifle-mk2": "Assault Rifle",
  "carbinerifle": "Assault Rifle MK2",
  "carbinerifle-mk2": "Carabine Rifle MK2",
  "advancedrifle": "Advanced Rifle",
  "specialcarbine": "Special Carabine",
  "specialcarbine-mk2": "Special Carabine MK2",
  "bullpuprifle": "Bullpup Rifle",
  "bullpuprifle-mk2": "Bullpup Rifle MK2",
  "compactrifle": "Compact Rifle",
  "mg": "MG",
  "combatmg": "Combat MG",
  "combatmg-mk2": "Combat MG MK2",
  "gusenberg": "Gusenberg",
  "sniperrifle": "Sniper Rifle",
  "heavysniper": "Heavy Sniper",
  "heavysniper-mk2": "Heavy Sniper MK2",
  "marksmanrifle": "Marksman Rifle",
  "marksmanrifle-mk2": "Marksman Rifle MK2",
  "rpg": "RPG",
  "grenadelauncher": "Grenade Launcher",
  "smokegrenadelauncher": "Smoke Greande Launcher",
  "minigun": "Minigun",
  "fireworklauncher": "Firework Launcher",
  "railgun": "Railgun",
  "hominglauncher": "Homing Laucher",
  "compactgrenadelauncher": "Compact Grenade Launcher",
  "rayminigun": "Ray Minigun",
  "grenade": "Grenade",
  "bzgas": "Bzgas",
  "smokegrenade": "Smoke Grenade",
  "flare": "Flare",
  "molotov": "Molotov",
  "stickybomb": "Sticky Bomb",
  "proximitymine": "Proximity Mine",
  "snowball": "Showball",
  "pipebomb": "Pipe Bomb",
  "baseball": "Baseball",
  "jerrycan": "Jerrycan",
  "fireextinguisher": "Fireextinguisher",
  "parachute": "Parachute",
  "electricfence": "Electricfence",
}

const weaponSlot = {
  [WeaponSlot.primary]: 1,
  [WeaponSlot.secondary]: 2,
  [WeaponSlot.melee]: 3,
  [WeaponSlot.unarmed]: 4,
}

const typeCategory = {
  melee: 'Buy Melee (Melee Weapon)',
  pistols: 'Buy Pistol (Secondary Weapon)',
  submachine_guns: 'Buy SMG (Primary Weapon)',
  shotguns: 'Buy Shotgun (Primary Weapon)',
  assault_rifles: 'Buy Assault Rifle (Primary Weapon)',
  light_rifles: 'Buy Light Rifle (Primary Weapon)',
  sniper_rifles: 'Buy Sniper Rifle (Primary Weapon)',
}

export { weaponNames, weaponSlot, typeCategory }